server:
  port: 9106
spring:
  application:
    name: API-SEARCH
  cloud:
    nacos:
      server-addr: 192.168.154.101:8848

  rabbitmq:
    host: 192.168.154.101
    port: 5672
    username: guest
    password: guest
    virtual-host: /

esConfig:
  addr: 192.168.154.101:9200

logging:
  level:
    com.tree3.controller: debug
